### ISSUE TITLE
pip install?

### ISSUE THREAD

**Issue by OrionRandD** [yafeunteun/anki2orgdrill#2]
How to install with pip?

pip install anki2orgdrill

Does not work and I would like to install it system-wide

sudo pip install anki2orgdrill

**Comment by yfe404** [comment]
Hello, it is not supposed to be installed with pip (yet), but I can implement it. For now what you can do is simply move the script in a location that is in your system's PATH and make it executable.

**Comment by OrionRandD** [comment]
Ok. I will wait for the pip implamentation...
I tried the other way and did not work.
Since I want to install it system-wide

**Comment by nfedyashev** [comment]
Hi @yfe404 ! Thanks for this really neat tool!

I'm not a python developer so it took a while to figure out how to run it. Not sure if it makes sense to put it to README. That's what I did

```
python3 -m pip install click
python3 a2od.py convert ~/Downloads/AllDecks.txt decks.org
```

**Comment by OrionRandD** [comment]
thx a lot :)

**Comment by yfe404** [comment]
Hi @nfedyashev thank you for your interest and for the suggestion :) 

As @OrionRandD asked for I published the project on [PyPI](https://pypi.org/project/a2od/) so now the installation is simpler, you just need to `pip install a2od` and then you can use it like that: `a2od convert ~/Downloads/AllDecks.txt decks.org`

I updated the documentation accordingly, please let me know if something goes wrong, also do not hesitate to pull request :)
